# Generated by Django 3.0.8 on 2020-08-10 14:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=datetime.datetime(2020, 8, 10, 14, 20, 49, 998643, tzinfo=utc))),
                ('finish_date', models.DateField(default=datetime.datetime(2020, 8, 11, 14, 20, 49, 998643, tzinfo=utc))),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='status.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=datetime.datetime(2020, 8, 10, 14, 20, 49, 999638, tzinfo=utc))),
                ('finish_date', models.DateField(default=datetime.datetime(2020, 8, 11, 14, 20, 49, 999638, tzinfo=utc))),
                ('is_zero', models.BooleanField(blank=True, default=False)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='projects.Project')),
                ('root_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='projects.Level')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='status.Status')),
            ],
        ),
    ]
