# Generated by Django 3.0.8 on 2020-08-10 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 11, 14, 21, 0, 271670, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='level',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 10, 14, 21, 0, 271670, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 11, 14, 21, 0, 271670, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 10, 14, 21, 0, 271670, tzinfo=utc)),
        ),
    ]
