# Generated by Django 3.0.8 on 2020-08-10 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200810_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 11, 15, 58, 42, 729552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='level',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 10, 15, 58, 42, 729552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 11, 15, 58, 42, 729552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 10, 15, 58, 42, 729552, tzinfo=utc)),
        ),
    ]
