version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  the-projects:
    image: rtuitlab/the-projects
    environment:
      - DATABASE_HOST=database
    depends_on:
      - database
    ports:
      - 8008:80

volumes:
  postgres_volume:
