# Generated by Django 3.0.8 on 2020-07-15 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='task',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 16, 19, 14, 35, 374145, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 15, 19, 14, 35, 374114, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.Status'),
        ),
    ]
