# Generated by Django 3.0.8 on 2020-07-17 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200715_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 18, 7, 30, 7, 79403, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 17, 7, 30, 7, 79374, tzinfo=utc)),
        ),
    ]
