# Generated by Django 3.0.8 on 2020-07-17 08:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('tasks', '0005_auto_20200717_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 18, 8, 4, 48, 305667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 17, 8, 4, 48, 305636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='status.Status'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
