# Generated by Django 3.0.8 on 2020-07-22 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200717_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 23, 11, 27, 0, 706696, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 22, 11, 27, 0, 706696, tzinfo=utc)),
        ),
    ]
