# Generated by Django 3.0.8 on 2020-08-10 14:20

from django.db import migrations, models
import status.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('color', status.fields.ColorField(default='#FFFFFF', max_length=7, verbose_name='Color')),
            ],
        ),
    ]
