# Generated by Django 3.0.8 on 2020-07-22 11:27

from django.db import migrations
import status.fields


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=status.fields.ColorField(default='#FF0000', max_length=7, verbose_name='Color'),
        ),
    ]
